import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('devdeck', {
  listProjects: () => ipcRenderer.invoke('projects:list'),
  setNote: (path: string, note: string) => ipcRenderer.invoke('project:setNote', path, note),
  setTodos: (path: string, todos: unknown) => ipcRenderer.invoke('project:setTodos', path, todos),
  setPinned: (path: string, pinned: boolean) => ipcRenderer.invoke('project:setPinned', path, pinned),
  setHidden: (path: string, hidden: boolean) => ipcRenderer.invoke('project:setHidden', path, hidden),
  open: (items: { path: string; sessionId: string | null }[]) => ipcRenderer.invoke('projects:open', items),
  onError: (cb: (msg: string) => void) =>
    ipcRenderer.on('devdeck:error', (_e, msg: string) => cb(msg)),
  usageReport: (sinceMs: number) => ipcRenderer.invoke('usage:report', sinceMs),
  getLanguage: () => ipcRenderer.invoke('settings:getLanguage'),
  setLanguage: (lang: string) => ipcRenderer.invoke('settings:setLanguage', lang),
  getAgent: () => ipcRenderer.invoke('settings:getAgent'),
  setAgent: (id: string) => ipcRenderer.invoke('settings:setAgent', id),
  availableAgents: () => ipcRenderer.invoke('settings:availableAgents'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setBaseDir: (dir: string) => ipcRenderer.invoke('settings:setBaseDir', dir),
  getFolders: () => ipcRenderer.invoke('settings:getFolders'),
  addFolder: (path: string) => ipcRenderer.invoke('settings:addFolder', path),
  removeFolder: (path: string) => ipcRenderer.invoke('settings:removeFolder', path),
  setThresholds: (t: { freshDays: number; warnDays: number; neglectedDays: number }) => ipcRenderer.invoke('settings:setThresholds', t),
  setOpenAtLogin: (enabled: boolean) => ipcRenderer.invoke('settings:setOpenAtLogin', enabled),
  pickFolder: () => ipcRenderer.invoke('settings:pickFolder'),
  openFolder: (path: string) => ipcRenderer.invoke('project:openFolder', path),
  openEditor: (path: string) => ipcRenderer.invoke('project:openEditor', path),
  openRepo: (path: string) => ipcRenderer.invoke('project:openRepo', path),
  createProject: (parent: string, name: string) => ipcRenderer.invoke('project:create', parent, name),
  setViewMode: (mode: 'cards' | 'list') => ipcRenderer.invoke('settings:setViewMode', mode),
  setCockpitSidebar: (collapsed: boolean) => ipcRenderer.invoke('settings:setCockpitSidebar', collapsed),
  usageWindows: () => ipcRenderer.invoke('usage:windows'),
  onUpdate: (cb: (p: import('../shared/update').UpdatePayload) => void) =>
    ipcRenderer.on('devdeck:update', (_e, p) => cb(p as import('../shared/update').UpdatePayload)),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  setPendingAutoRestore: (sessions: unknown) => ipcRenderer.invoke('update:setPendingAutoRestore', sessions),
  consumeAutoRestore: () => ipcRenderer.invoke('update:consumeAutoRestore'),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  openExternal: (url: string) => ipcRenderer.invoke('shell:openExternal', url),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  windowControls: {
    show: () => ipcRenderer.invoke('win:show'),
    minimize: () => ipcRenderer.invoke('win:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('win:toggleMaximize'),
    close: () => ipcRenderer.invoke('win:close'),
    isMaximized: () => ipcRenderer.invoke('win:isMaximized'),
    onMaximizeChange: (cb: (maximized: boolean) => void) =>
      ipcRenderer.on('win:maximize-changed', (_e, m: boolean) => cb(m)),
  },
  clipboard: {
    writeText: (text: string) => ipcRenderer.send('clipboard:writeText', text),
    readText: (): Promise<string> => ipcRenderer.invoke('clipboard:readText'),
    readImage: (): Promise<string | null> => ipcRenderer.invoke('clipboard:readImage'),
  },
  cockpit: {
    open: (req: { projectPath: string; sessionId: string | null; cols: number; rows: number; fresh?: boolean }) =>
      ipcRenderer.invoke('cockpit:open', req),
    input: (id: string, data: string) => ipcRenderer.send('cockpit:input', id, data),
    resize: (id: string, cols: number, rows: number) => ipcRenderer.send('cockpit:resize', id, cols, rows),
    close: (id: string) => ipcRenderer.send('cockpit:close', id),
    onData: (cb: (p: { id: string; chunk: string }) => void) =>
      ipcRenderer.on('cockpit:data', (_e, p) => cb(p)),
    onExit: (cb: (p: { id: string; exitCode: number }) => void) =>
      ipcRenderer.on('cockpit:exit', (_e, p) => cb(p)),
    loadSessions: () => ipcRenderer.invoke('cockpit:loadSessions'),
    saveSessions: (list: unknown) => ipcRenderer.send('cockpit:saveSessions', list),
    sessionMeta: (projectPath: string, sessionId: string) => ipcRenderer.invoke('cockpit:sessionMeta', projectPath, sessionId),
    sessionIds: (projectPath: string) => ipcRenderer.invoke('cockpit:sessionIds', projectPath),
    liveSessionId: (projectPath: string, opts: { currentId: string | null; claimedIds: string[]; openedAtMs: number; sinceMs: number; lastDataAtMs: number }) =>
      ipcRenderer.invoke('cockpit:liveSessionId', projectPath, opts),
    gitInfo: (projectPath: string) => ipcRenderer.invoke('cockpit:gitInfo', projectPath),
    openLink: (url: string) => ipcRenderer.invoke('cockpit:openLink', url),
    openFile: (projectPath: string, filePath: string) => ipcRenderer.invoke('cockpit:openFile', projectPath, filePath),
  },
  shutdown: {
    arm: () => ipcRenderer.invoke('shutdown:arm'),
    disarm: () => ipcRenderer.invoke('shutdown:disarm'),
    now: () => ipcRenderer.invoke('shutdown:now'),
    cancel: () => ipcRenderer.invoke('shutdown:cancel'),
    status: () => ipcRenderer.invoke('shutdown:status'),
    history: () => ipcRenderer.invoke('shutdown:history'),
    bootBanner: () => ipcRenderer.invoke('shutdown:bootBanner'),
    ackBanner: () => ipcRenderer.invoke('shutdown:ackBanner'),
    setIdleMinutes: (m: number) => ipcRenderer.invoke('shutdown:setIdleMinutes', m),
    report: (p: { working: number; sessions: { project: string; activity: string }[] }) => ipcRenderer.send('shutdown:report', p),
    onStatus: (cb: (s: unknown) => void) => ipcRenderer.on('shutdown:status', (_e, s) => cb(s)),
  },
  setTrayAlert: (mode: string) => ipcRenderer.invoke('settings:setTrayAlert', mode),
  setContextWindow: (w: number) => ipcRenderer.invoke('settings:setContextWindow', w),
  setTrayCounts: (counts: { attention?: number; turn?: number; overdue?: number }) => ipcRenderer.send('tray:counts', counts),
  setTrayAlertImage: (dataUrl: string) => ipcRenderer.send('tray:alertImage', dataUrl),
});
